# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7e1221ce349656a274fb5de2ab0920ed24212458c801435e084078079c980ef1701bd516ee21fefee9ff53d22cb3b1a3009c8a0dac357f8cb92852022a30f1d

test:
  secret_key_base: bb35cc04183ed239388b2dfbb95ee28d771028c0e3f86dc2944a4f89f4f73c5e778a743be40aa900a150cd0082cdba76e0886495c963d74e709f97c8728647cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
